### ISSUE TITLE
Подсказки перекрываются автозаполнением Google Chrome.

### ISSUE THREAD

**Issue by Xumukk** [troyanov/woocommerce-dadata#1]
Подсказки перекрываются автозаполнением Google Chrome.
![image](https://user-images.githubusercontent.com/26875529/53230569-0b0f6d00-3698-11e9-9823-01c18e48beac.png)

**Comment by troyanov** [comment]
@Xumukk если еще актуально, то вы можете попробовать исправить это обсуждаемыми здесь способами https://stackoverflow.com/questions/15738259/disabling-chrome-autofill
