### ISSUE TITLE
Подскажите как убрать автозаполнение с имени и е-мейл

### ISSUE THREAD

**Issue by shinsei22** [troyanov/woocommerce-dadata#2]
Добрый день, хочу убрать автозаполнения с этих полей, подскажите, пожалуйста как это можно сдлетаь

**Comment by troyanov** [comment]
@shinsei22 в файле `custom/custom.js` вы можете убрать инициализацию для соответствующих элементов. Например для отключения подсказок к полю e-mail просто удалите

```
$("#billing_email").suggestions({
		serviceUrl: "https://suggestions.dadata.ru/suggestions/api/4_1/rs",
		token: php_vars.dadata_suggest_token,
		type: "EMAIL",
		count: 5,
	});
```

Для имени плательщика/получателя соответственно 
`billing_first_name`
`shipping_first_name`
