### ISSUE TITLE
Приложения wordpress

### ISSUE THREAD

**Issue by Ybelyavsky** [troyanov/woocommerce-dadata#3]
Не нашел плагин в магазине приложений, добавьте, пожалуйста.

**Comment by troyanov** [comment]
> Не нашел плагин в магазине приложений, добавьте, пожалуйста.

@Ybelyavsky наличие плагина в магазине приложений подразумевает что пользователи будут ожидать поддержки от разработчиков. К сожалению у меня на это нет ни времени ни ресурсов и я не могу давать каких-либо гарантий на счет поддерживаемых версий (а без этого модерация очень быстро отклоняет заявку на добавление плагина в маркет).

Я попробую связаться с ребятами из dadata.ru, если им это будет интересно, то я передам им права на код и они опубликуют плагин в маркет. В конце концов это они предоставляют платный сервис на котором они зарабатывают деньги, а не я :-)

**Comment by Ybelyavsky** [comment]
Плагин очень тормозит сайт и жрет процессорную мощность, идут бесконечные фоновые процессы видимо?

**Comment by troyanov** [comment]
> Плагин очень тормозит сайт и жрет процессорную мощность, идут бесконечные фоновые процессы видимо?

@Ybelyavsky почему Вы уверены что это именно этот плагин? Он весьма простой и лишь добавляет автокомплит на клиентской стороне. Никаких фоновых процессов в нем нет. При начале ввода отправляется запрос в DaData API и рендерит выпадающий список. 

Возможно проблема в чём-то другом?

Есть ссылка с веб-сайтом на котором установлен этот плагин? Могу глянуть что там web inspector показывает...

**Comment by Ybelyavsky** [comment]
ronbel.ru вы можете взять заказ на оптимизацию загрузки сайта? 
Я вроде бы предварительно [нашел проблему ](https://qna.habr.com/questionversion?question_id=1182382&e=12904264#version_1535332)

**Comment by troyanov** [comment]
> вы можете взять заказ на оптимизацию загрузки сайта?

Увы, я занимаюсь совершенно другими вещами и к веб-сайтам интереса вообще никакого нет.
